micronaut:
  application:
    name: keyManager

itau:
  contas:
    url: http://localhost:9091/api/v1

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pixdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true